name: Report a Bug
description: Report a StarCosmetics Bug.
labels: ['unconfirmed bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a StarCosmetics bug. Please take time to fill out the information below.
  - type: dropdown
    attributes:
      label: Bug Type
      description: What type of bug are you trying to report?
      multiple: true
      options:
        - Performance / Memory Leak / Server Crash
        - Compatibility Issues
        - General Bug
        - Console Errors
        - Other Unexpected Behavior
    validations:
      required: true

  - type: input
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you using?
      placeholder: |
        Ex: 1.19
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      placeholder: |
        Ex: "Cosmetic not displaying correctly."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expect the plugin to do.
      placeholder: |
        Ex: "Green cosmetic should be displayed."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What does the plugin do? What are the error messages shown?
      placeholder: |
        Ex: "Blue is shown instead of green."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other Information
      description: Attach any other relevant info or files that may help us solve the bug, as well as any other information.
      placeholder: |
        Ex: "Console errors, screenshots, etc."
    validations:
      required: false
